from pathlib import Path
import re

INPUT_FILE = Path("myRefs.bib")
OUTPUT_FILE = Path("myRefs-web.bib")


STRING_LINE_RE = re.compile(
    r"""
    ^\s*
    @string
    \s*\{
    \s*(?P<name>[A-Za-z_][A-Za-z0-9_:\-]*)
    \s*=\s*
    (?P<value>.+)
    \}
    \s*$
    """,
    re.IGNORECASE | re.VERBOSE,
)

COMMENT_LINE_RE = re.compile(
    r"^\s*@comment\s*\{.*\}\s*$",
    re.IGNORECASE,
)


def unwrap_value(value: str) -> str:
    """
    Remove the outer braces or quotes from an @string value.

    Example:
        {{IEEE} Trans. Robotics}
    becomes:
        {IEEE} Trans. Robotics
    """
    value = value.strip().rstrip(",").strip()

    if value.startswith("{") and value.endswith("}"):
        return value[1:-1]

    if value.startswith('"') and value.endswith('"'):
        return value[1:-1]

    return value


def extract_strings_and_clean(text: str) -> tuple[dict[str, str], str]:
    """
    Extract one-line @string declarations while preserving all
    publication entries.
    """
    strings: dict[str, str] = {}
    retained_lines: list[str] = []

    for line_number, line in enumerate(text.splitlines(), start=1):
        string_match = STRING_LINE_RE.match(line)

        if string_match:
            name = string_match.group("name").lower()
            value = unwrap_value(string_match.group("value"))
            strings[name] = value
            continue

        if COMMENT_LINE_RE.match(line):
            continue

        retained_lines.append(line)

    return strings, "\n".join(retained_lines) + "\n"


def expand_string_fields(text: str, strings: dict[str, str]) -> str:
    """
    Expand bare @string identifiers in venue-related fields.

    Example:
        booktitle = rss,

    becomes:
        booktitle = {Robotics: Science and Systems (RSS)},
    """
    fields = (
        "journal",
        "booktitle",
        "publisher",
        "institution",
        "school",
        "organization",
        "series",
        "address",
    )

    field_names = "|".join(re.escape(field) for field in fields)

    pattern = re.compile(
        rf"""
        (?P<prefix>
            \b(?:{field_names})
            \s*=\s*
        )
        (?P<identifier>
            [A-Za-z_][A-Za-z0-9_:\-]*
        )
        (?P<suffix>
            \s*(?:,|\}})
        )
        """,
        re.IGNORECASE | re.VERBOSE,
    )

    def replacement(match: re.Match[str]) -> str:
        identifier = match.group("identifier")
        expanded = strings.get(identifier.lower())

        if expanded is None:
            return match.group(0)

        return (
            f"{match.group('prefix')}"
            f"{{{expanded}}}"
            f"{match.group('suffix')}"
        )

    return pattern.sub(replacement, text)


def count_publications(text: str) -> int:
    """
    Count bibliography records while excluding @string and @comment.
    """
    entry_pattern = re.compile(
        r"^\s*@(?!string\b|comment\b|preamble\b)[A-Za-z]+\s*[\{\(]",
        re.IGNORECASE | re.MULTILINE,
    )
    return len(entry_pattern.findall(text))


def main() -> None:
    if not INPUT_FILE.exists():
        raise FileNotFoundError(
            f"Could not find {INPUT_FILE.resolve()}"
        )

    source = INPUT_FILE.read_text(encoding="utf-8")

    input_entries = count_publications(source)
    strings, cleaned = extract_strings_and_clean(source)
    expanded = expand_string_fields(cleaned, strings)
    output_entries = count_publications(expanded)

    if input_entries == 0:
        raise RuntimeError(
            "No publication entries were found in myRefs.bib."
        )

    if output_entries != input_entries:
        raise RuntimeError(
            "Publication count changed during conversion: "
            f"{input_entries} input entries versus "
            f"{output_entries} output entries."
        )

    header = (
        "% This file is generated automatically from myRefs.bib.\n"
        "% Do not edit this file directly.\n\n"
    )

    OUTPUT_FILE.write_text(
        header + expanded.lstrip(),
        encoding="utf-8",
    )

    print(
        f"Wrote {OUTPUT_FILE} with "
        f"{len(strings)} string definitions expanded "
        f"across {output_entries} publication entries."
    )


if __name__ == "__main__":
    main()