from pathlib import Path
import re

INPUT_FILE = Path("myRefs.bib")
OUTPUT_FILE = Path("myRefs-web.bib")


def find_balanced_block(text: str, start: int) -> tuple[str, int]:
    """
    Return the contents of a brace-delimited block and the index
    immediately after its closing brace.
    """
    if text[start] != "{":
        raise ValueError("Expected opening brace")

    depth = 0

    for i in range(start, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1

            if depth == 0:
                return text[start + 1:i], i + 1

    raise ValueError("Unbalanced braces")


def extract_string_definitions(text: str) -> tuple[dict[str, str], str]:
    """
    Extract @string definitions and remove them from the bibliography.
    """
    strings: dict[str, str] = {}
    output_parts: list[str] = []

    pattern = re.compile(r"@string\s*\{", re.IGNORECASE)
    position = 0

    while True:
        match = pattern.search(text, position)

        if match is None:
            output_parts.append(text[position:])
            break

        output_parts.append(text[position:match.start()])

        opening_brace = match.end() - 1
        contents, end = find_balanced_block(text, opening_brace)

        name, separator, value = contents.partition("=")

        if not separator:
            raise ValueError(f"Malformed @string definition: {contents}")

        name = name.strip().lower()
        value = value.strip()

        if value.startswith("{") and value.endswith("}"):
            value = value[1:-1]
        elif value.startswith('"') and value.endswith('"'):
            value = value[1:-1]

        strings[name] = value
        position = end

    return strings, "".join(output_parts)


def remove_comment_entries(text: str) -> str:
    """
    Remove BibDesk @comment records, which are not needed by the website.
    """
    pattern = re.compile(r"@comment\s*\{", re.IGNORECASE)
    output_parts: list[str] = []
    position = 0

    while True:
        match = pattern.search(text, position)

        if match is None:
            output_parts.append(text[position:])
            break

        output_parts.append(text[position:match.start()])

        opening_brace = match.end() - 1
        _, end = find_balanced_block(text, opening_brace)
        position = end

    return "".join(output_parts)


def expand_string_fields(text: str, strings: dict[str, str]) -> str:
    """
    Replace bare string identifiers in common bibliographic fields.

    Example:
        journal = tro

    becomes:
        journal = {{IEEE} Trans. Robotics}
    """
    fields = (
        "journal",
        "booktitle",
        "publisher",
        "institution",
        "school",
        "organization",
        "series",
    )

    field_pattern = "|".join(fields)

    pattern = re.compile(
        rf"(?P<prefix>\b(?:{field_pattern})\s*=\s*)"
        rf"(?P<value>[A-Za-z_][A-Za-z0-9_:\-]*)"
        rf"(?P<suffix>\s*[,}}])",
        re.IGNORECASE,
    )

    def replace(match: re.Match[str]) -> str:
        identifier = match.group("value")
        expanded = strings.get(identifier.lower())

        if expanded is None:
            return match.group(0)

        return (
            f"{match.group('prefix')}"
            f"{{{expanded}}}"
            f"{match.group('suffix')}"
        )

    return pattern.sub(replace, text)


def main() -> None:
    text = INPUT_FILE.read_text(encoding="utf-8")

    strings, text_without_strings = extract_string_definitions(text)
    text_without_comments = remove_comment_entries(text_without_strings)
    expanded = expand_string_fields(text_without_comments, strings)

    header = (
        "% This file is generated automatically from myRefs.bib.\n"
        "% Do not edit this file directly.\n\n"
    )

    OUTPUT_FILE.write_text(header + expanded.lstrip(), encoding="utf-8")

    print(
        f"Wrote {OUTPUT_FILE} with "
        f"{len(strings)} expanded string definitions."
    )


if __name__ == "__main__":
    main()